apiVersion: apps/v1
kind: Deployment
metadata:
  name: q6
  labels: 
    app: q6-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: q6-FinalExam
  template:
    metadata:
      labels:
        app: q6-FinalExam
    spec:
      containers:
      - name: q6
        image: shubham0210/devops_final_q2
        # In case we have the image in local repository we can uncomment the following line and use local image name 
        # imagePullPolicy: IfNotPresent
