apiVersion: v1
kind: Service
metadata:
  name: q6-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: q6-FinalExam